name: Deployment Pepiline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

env: 
  TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
  TEST_PORT: ${{secrets.TEST_PORT}}
  SECRET: ${{secrets.SECRET}}

jobs:
  avoid_reduncy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previus Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{secrets.GIT_TOKEN}}

  lint-job:
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: npm install
        run: npm ci
      - name: lint
        run: npm run eslint
  
  build-job:
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: npm install
        run: npm ci
      - name: npm build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./app/dist
      - name: Build fieled notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Build Failed!!!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  test-job:
    needs: [build-job, lint-job]
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: npm ci
        run: npm ci
      - name: download build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./app/dist
      - name: test
        run: npm run test
      - name: Test fieled notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Test Failed!!!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  test-e2e-job:
    needs: [build-job, lint-job]
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: npm install
        run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./app/dist
      - name: test-e2e
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start:test
          wait-on: http://localhost:${{secrets.TEST_PORT}}
      - name: Test fieled notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Test e2e Failed!!!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  
  deployment-job:
    needs: [test-job, test-e2e-job]
    if: ${{github.event_name == 'push' && !contains(join(github.event.commits.*.message,' '),'#skip')}}
    runs-on: ubuntu-20.04
    steps:
      - name: extrayendo el repositorio
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}

  new-deploy-notification:
    needs: deployment-job
    runs-on: ubuntu-20.04
    steps:
      - name: new deploy notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            details: A new version of bloglistapp deployed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [deployment-job]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,' '),'#skip')}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
      
